# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

# Part 1: Dataset Creation

In [1]:
import numpy as np
import pandas as pd

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

df_sales=pd.DataFrame(sales_data,index=stores,columns=categories)
print("\n",df_sales)

df_cost=pd.DataFrame(cost_data,index=stores,columns=categories)
print("\n",df_cost)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderabad       780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  2

# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

In [2]:
print("Number of dimensions:", sales_data.ndim)
print("Shape:", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type:", sales_data.dtype)
print("Memory occupied:", sales_data.nbytes, "bytes")

Number of dimensions: 2
Shape: (5, 6)
Total number of values: 30
Data type: int64
Memory occupied: 240 bytes


## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

In [3]:
print("Total stores:", len(stores))
print("Total product categories:", len(categories))
print("Total store-category combinations:", sales_data.size)

Total stores: 5
Total product categories: 6
Total store-category combinations: 30


## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

In [4]:
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)
print("float32 memory:", sales_float32.nbytes, "bytes")
print("float64 memory:", sales_float64.nbytes, "bytes")
print("Memory saved using float32:", sales_float64.nbytes - sales_float32.nbytes, "bytes")

float32 memory: 120 bytes
float64 memory: 240 bytes
Memory saved using float32: 120 bytes


# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [5]:
print(df_sales.loc["Bengaluru"])

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Sports         225000
Name: Bengaluru, dtype: int64


## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [6]:
print("Mumbai total cost:", df_cost.loc["Mumbai"].sum())

Mumbai total cost: 2065000


## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

In [7]:
print(df_sales["Electronics"])

Bengaluru     850000
Hyderabad     780000
Chennai       920000
Mumbai       1050000
Pune          690000
Name: Electronics, dtype: int64


## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

In [8]:
print(df_cost["Clothing"])

Bengaluru    220000
Hyderabad    210000
Chennai      245000
Mumbai       265000
Pune         205000
Name: Clothing, dtype: int64


## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

In [9]:
furniture_sales = df_sales.loc["Hyderabad", "Furniture"]
furniture_cost = df_cost.loc["Hyderabad", "Furniture"]
furniture_profit = furniture_sales - furniture_cost
print("Furniture sales:", furniture_sales)
print("Furniture cost:", furniture_cost)
print("Furniture profit:", furniture_profit)

Furniture sales: 310000
Furniture cost: 225000
Furniture profit: 85000


## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

In [10]:
chennai_slice = sales_data[2, 1:4]
print("Chennai Groceries, Clothing, Furniture:", chennai_slice)

Chennai Groceries, Clothing, Furniture: [390000 340000 260000]


## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

In [11]:
selected = sales_data[[0, 2, 4]][:, [0, 2, 4]]
print(pd.DataFrame(selected, index=stores[[0,2,4]], columns=categories[[0,2,4]]))

           Electronics  Clothing  Beauty
Bengaluru       850000    310000  190000
Chennai         920000    340000  185000
Pune            690000    280000  175000


# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [12]:
total_sales = sales_data.sum()
print("Company-wide total sales:", total_sales)

Company-wide total sales: 11675000


## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [13]:
store_sales = sales_data.sum(axis=1)
for store, total in zip(stores, store_sales):
    print(f"{store}: {total}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [14]:
category_sales = sales_data.sum(axis=0)
for category, total in zip(categories, category_sales):
    print(f"{category}: {total}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [15]:
store_avg_sales = sales_data.mean(axis=1)
for store, avg in zip(stores, store_avg_sales):
    print(f"{store}: {avg:.2f}")

Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00


## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [16]:
category_avg_sales = sales_data.mean(axis=0)
for category, avg in zip(categories, category_avg_sales):
    print(f"{category}: {avg:.2f}")

Electronics: 858000.00
Groceries: 437000.00
Clothing: 320000.00
Furniture: 283000.00
Beauty: 202000.00
Sports: 235000.00


## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

In [17]:
store_totals = sales_data.sum(axis=1)
idx = np.argmax(store_totals)
print("Index:", idx)
print("Store:", stores[idx])
print("Total sales:", store_totals[idx])

Index: 3
Store: Mumbai
Total sales: 2820000


## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

In [18]:
store_totals = sales_data.sum(axis=1)
idx = np.argmin(store_totals)
print("Lowest-selling store:", stores[idx])
print("Total sales:", store_totals[idx])

Lowest-selling store: Pune
Total sales: 1980000


## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [19]:
category_totals = sales_data.sum(axis=0)
idx = np.argmax(category_totals)
print("Highest-selling category:", categories[idx])
print("Total sales:", category_totals[idx])

Highest-selling category: Electronics
Total sales: 4290000


## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [20]:
category_totals = sales_data.sum(axis=0)
idx = np.argmin(category_totals)
print("Lowest-selling category:", categories[idx])
print("Total sales:", category_totals[idx])

Lowest-selling category: Beauty
Total sales: 1010000


# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [21]:
print("Total company cost:", cost_data.sum())

Total company cost: 8600000


## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [22]:
store_costs = cost_data.sum(axis=1)
for store, total in zip(stores, store_costs):
    print(f"{store}: {total}")

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [23]:
category_costs = cost_data.sum(axis=0)
for category, total in zip(categories, category_costs):
    print(f"{category}: {total}")

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [24]:
store_costs = cost_data.sum(axis=1)
idx = np.argmax(store_costs)
print("Most expensive store:", stores[idx])
print("Total cost:", store_costs[idx])

Most expensive store: Mumbai
Total cost: 2065000


## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [25]:
store_costs = cost_data.sum(axis=1)
idx = np.argmin(store_costs)
print("Lowest-cost store:", stores[idx])
print("Total cost:", store_costs[idx])

Lowest-cost store: Pune
Total cost: 1475000


## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [26]:
category_costs = cost_data.sum(axis=0)
idx = np.argmax(category_costs)
print("Most expensive product category:", categories[idx])
print("Total cost:", category_costs[idx])

Most expensive product category: Electronics
Total cost: 3250000


# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

```python
profit_data = sales_data - cost_data
```

Display the complete profit matrix.

In [27]:
profit_data = sales_data - cost_data
df_profit = pd.DataFrame(profit_data, index=stores, columns=categories)
print(df_profit)

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       210000     105000     90000      70000   65000   65000
Hyderabad       190000     110000     85000      85000   70000   70000
Chennai         220000      95000     95000      65000   65000   60000
Mumbai          260000     120000    110000      95000   85000   85000
Pune            160000      95000     75000      55000   60000   60000


## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [28]:
store_profit = profit_data.sum(axis=1)
for store, total in zip(stores, store_profit):
    print(f"{store}: {total}")

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [29]:
category_profit = profit_data.sum(axis=0)
for category, total in zip(categories, category_profit):
    print(f"{category}: {total}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


## Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

* Store name
* Total sales
* Total cost
* Total profit

In [30]:
store_sales = sales_data.sum(axis=1)
store_cost = cost_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)
idx = np.argmax(store_profit)
print("Store:", stores[idx])
print("Total sales:", store_sales[idx])
print("Total cost:", store_cost[idx])
print("Total profit:", store_profit[idx])

Store: Mumbai
Total sales: 2820000
Total cost: 2065000
Total profit: 755000


## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [31]:
store_profit = profit_data.sum(axis=1)
idx = np.argmin(store_profit)
print("Least profitable store:", stores[idx])
print("Total profit:", store_profit[idx])

Least profitable store: Pune
Total profit: 505000


## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [32]:
category_profit = profit_data.sum(axis=0)
idx = np.argmax(category_profit)
print("Most profitable category:", categories[idx])
print("Total profit:", category_profit[idx])

Most profitable category: Electronics
Total profit: 1040000


## Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [33]:
category_profit = profit_data.sum(axis=0)
idx = np.argmin(category_profit)
print("Least profitable category:", categories[idx])
print("Total profit:", category_profit[idx])

Least profitable category: Sports
Total profit: 340000


## Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

* Profit amount
* Store name
* Product category

Use `np.unravel_index()`.

In [34]:
flat_index = np.argmax(profit_data)
row_idx, col_idx = np.unravel_index(flat_index, profit_data.shape)
print("Profit:", profit_data[row_idx, col_idx])
print("Store:", stores[row_idx])
print("Category:", categories[col_idx])

Profit: 260000
Store: Mumbai
Category: Electronics


## Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [35]:
flat_index = np.argmin(profit_data)
row_idx, col_idx = np.unravel_index(flat_index, profit_data.shape)
print("Profit:", profit_data[row_idx, col_idx])
print("Store:", stores[row_idx])
print("Category:", categories[col_idx])

Profit: 55000
Store: Pune
Category: Furniture


# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

```python
profit_margin = (profit_data / sales_data) * 100
```

Round the result to two decimal places.

In [36]:
profit_margin = (profit_data / sales_data) * 100
print(pd.DataFrame(np.round(profit_margin, 2), index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        24.71      25.00     29.03      25.45   34.21   28.89
Hyderabad        24.36      23.91     28.81      27.42   33.33   29.17
Chennai          23.91      24.36     27.94      25.00   35.14   27.91
Mumbai           24.76      23.53     29.33      27.54   34.00   29.31
Pune             23.19      23.46     26.79      24.44   34.29   29.27


## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [37]:
store_profit_margin = (profit_data.sum(axis=1) / sales_data.sum(axis=1)) * 100
for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin:.2f}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [38]:
category_profit_margin = (profit_data.sum(axis=0) / sales_data.sum(axis=0)) * 100
for category, margin in zip(categories, category_profit_margin):
    print(f"{category}: {margin:.2f}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [39]:
idx = np.argmax(store_profit_margin)
print("Best store by profit margin:", stores[idx])
print("Profit margin:", store_profit_margin[idx])

Best store by profit margin: Mumbai
Profit margin: 26.773049645390074


## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [40]:
idx = np.argmax(category_profit_margin)
print("Best category by profit margin:", categories[idx])
print("Profit margin:", category_profit_margin[idx])

Best category by profit margin: Beauty
Profit margin: 34.15841584158416


## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

In [41]:
mask = profit_margin < 22
rows, cols = np.where(mask)
print("Store | Category | Sales | Cost | Profit | Profit Margin")
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]} | {cost_data[r,c]} | {profit_data[r,c]} | {profit_margin[r,c]:.2f}%")

Store | Category | Sales | Cost | Profit | Profit Margin


In [42]:
# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [43]:
mask = sales_data > 500000
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]}")

Bengaluru | Electronics | 850000
Hyderabad | Electronics | 780000
Chennai | Electronics | 920000
Mumbai | Electronics | 1050000
Mumbai | Groceries | 510000
Pune | Electronics | 690000


## Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [44]:
mask = sales_data < 200000
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]}")

Bengaluru | Beauty | 190000
Chennai | Beauty | 185000
Pune | Beauty | 175000


## Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [45]:
mask = profit_data > 150000
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | Profit: {profit_data[r,c]}")

Bengaluru | Electronics | Profit: 210000
Hyderabad | Electronics | Profit: 190000
Chennai | Electronics | Profit: 220000
Mumbai | Electronics | Profit: 260000
Pune | Electronics | Profit: 160000


## Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

In [46]:
mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]}")

Bengaluru | Groceries | 420000
Bengaluru | Clothing | 310000
Bengaluru | Furniture | 275000
Hyderabad | Groceries | 460000
Hyderabad | Clothing | 295000
Hyderabad | Furniture | 310000
Chennai | Groceries | 390000
Chennai | Clothing | 340000
Chennai | Furniture | 260000
Mumbai | Clothing | 375000
Mumbai | Furniture | 345000
Mumbai | Beauty | 250000
Mumbai | Sports | 290000
Pune | Groceries | 405000
Pune | Clothing | 280000


## Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

In [47]:
mask = np.logical_and(sales_data > 500000, profit_data > 150000)
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | Sales: {sales_data[r,c]} | Profit: {profit_data[r,c]}")

Bengaluru | Electronics | Sales: 850000 | Profit: 210000
Hyderabad | Electronics | Sales: 780000 | Profit: 190000
Chennai | Electronics | Sales: 920000 | Profit: 220000
Mumbai | Electronics | Sales: 1050000 | Profit: 260000
Pune | Electronics | Sales: 690000 | Profit: 160000


## Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

In [48]:
mask = np.logical_and(sales_data < 250000, profit_margin < 25)
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | Sales: {sales_data[r,c]} | Profit Margin: {profit_margin[r,c]:.2f}%")

Pune | Furniture | Sales: 225000 | Profit Margin: 24.44%


## Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

In [49]:
classification = np.select(
    [sales_data >= 500000,
     (sales_data >= 250000) & (sales_data < 500000)],
    ["High", "Medium"],
    default="Low"
)
print(pd.DataFrame(classification, index=stores, columns=categories))

          Electronics Groceries Clothing Furniture  Beauty  Sports
Bengaluru        High    Medium   Medium    Medium     Low     Low
Hyderabad        High    Medium   Medium    Medium     Low     Low
Chennai          High    Medium   Medium    Medium     Low     Low
Mumbai           High      High   Medium    Medium  Medium  Medium
Pune             High    Medium   Medium       Low     Low     Low


# Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [50]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

## Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

In [51]:
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 250000])
target_difference = sales_data - sales_targets
print(pd.DataFrame(target_difference, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        50000     -30000    -10000     -25000  -10000  -25000
Hyderabad       -20000      10000    -25000      10000   10000  -10000
Chennai         120000     -60000     20000     -40000  -15000  -35000
Mumbai          250000      60000     55000      45000   50000   40000
Pune           -110000     -45000    -40000     -75000  -25000  -45000


## Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

In [52]:
target_achievement = sales_data >= sales_targets
print(pd.DataFrame(target_achievement, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru         True      False     False      False   False   False
Hyderabad        False       True     False       True    True   False
Chennai           True      False      True      False   False   False
Mumbai            True       True      True       True    True    True
Pune             False      False     False      False   False   False


## Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [53]:
target_count = target_achievement.sum(axis=1)
for store, count in zip(stores, target_count):
    print(f"{store}: {count}")

Bengaluru: 1
Hyderabad: 3
Chennai: 2
Mumbai: 6
Pune: 0


## Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [54]:
target_count = target_achievement.sum(axis=1)
idx = np.argmax(target_count)
print("Best target-performing store:", stores[idx])
print("Targets achieved:", target_count[idx])

Best target-performing store: Mumbai
Targets achieved: 6


## Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [55]:
category_target_count = target_achievement.sum(axis=0)
for category, count in zip(categories, category_target_count):
    print(f"{category}: {count} stores")

Electronics: 3 stores
Groceries: 2 stores
Clothing: 2 stores
Furniture: 2 stores
Beauty: 2 stores
Sports: 1 stores


## Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use: Variance = Actual Sales - Target Sales

In [56]:
target_variance = sales_data - sales_targets
print(pd.DataFrame(target_variance, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        50000     -30000    -10000     -25000  -10000  -25000
Hyderabad       -20000      10000    -25000      10000   10000  -10000
Chennai         120000     -60000     20000     -40000  -15000  -35000
Mumbai          250000      60000     55000      45000   50000   40000
Pune           -110000     -45000    -40000     -75000  -25000  -45000


## Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

Percentage Variance = (Actual Sales - Target Sales) / Target Sales × 100

In [57]:
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100
print(pd.DataFrame(np.round(percentage_variance, 2), index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru         6.25      -6.67     -3.12      -8.33    -5.0   -10.0
Hyderabad        -2.50       2.22     -7.81       3.33     5.0    -4.0
Chennai          15.00     -13.33      6.25     -13.33    -7.5   -14.0
Mumbai           31.25      13.33     17.19      15.00    25.0    16.0
Pune            -13.75     -10.00    -12.50     -25.00   -12.5   -18.0


## Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [58]:
electronics_sales = sales_data[:, 0]
missing = stores[electronics_sales < sales_targets[0]]
print("Stores missing Electronics target:", missing)

Stores missing Electronics target: ['Hyderabad' 'Pune']


## Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use `np.all()`.

In [59]:
all_targets = np.all(target_achievement, axis=1)
for store, achieved in zip(stores, all_targets):
    print(f"{store}: {achieved}")

Bengaluru: False
Hyderabad: False
Chennai: False
Mumbai: True
Pune: False


## Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

In [60]:
any_targets = np.any(target_achievement, axis=1)
for store, achieved in zip(stores, any_targets):
    print(f"{store}: {achieved}")

Bengaluru: True
Hyderabad: True
Chennai: True
Mumbai: True
Pune: False


# Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [61]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

## Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

In [62]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
print(pd.DataFrame(discount_amount, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture   Beauty   Sports
Bengaluru      85000.0    21000.0   46500.0    33000.0  15200.0  22500.0
Hyderabad      78000.0    23000.0   44250.0    37200.0  16800.0  24000.0
Chennai        92000.0    19500.0   51000.0    31200.0  14800.0  21500.0
Mumbai        105000.0    25500.0   56250.0    41400.0  20000.0  29000.0
Pune           69000.0    20250.0   42000.0    27000.0  14000.0  20500.0


## Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [63]:
net_sales = sales_data - discount_amount
print(pd.DataFrame(net_sales, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture    Beauty    Sports
Bengaluru     765000.0   399000.0  263500.0   242000.0  174800.0  202500.0
Hyderabad     702000.0   437000.0  250750.0   272800.0  193200.0  216000.0
Chennai       828000.0   370500.0  289000.0   228800.0  170200.0  193500.0
Mumbai        945000.0   484500.0  318750.0   303600.0  230000.0  261000.0
Pune          621000.0   384750.0  238000.0   198000.0  161000.0  184500.0


## Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [64]:
new_profit = net_sales - cost_data
print(pd.DataFrame(new_profit, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture   Beauty   Sports
Bengaluru     125000.0    84000.0   43500.0    37000.0  49800.0  42500.0
Hyderabad     112000.0    87000.0   40750.0    47800.0  53200.0  46000.0
Chennai       128000.0    75500.0   44000.0    33800.0  50200.0  38500.0
Mumbai        155000.0    94500.0   53750.0    53600.0  65000.0  56000.0
Pune           91000.0    74750.0   33000.0    28000.0  46000.0  39500.0


## Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

In [65]:
discounted_profit_margin = (new_profit / net_sales) * 100
print(pd.DataFrame(np.round(discounted_profit_margin, 2), index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        16.34      21.05     16.51      15.29   28.49   20.99
Hyderabad        15.95      19.91     16.25      17.52   27.54   21.30
Chennai          15.46      20.38     15.22      14.77   29.49   19.90
Mumbai           16.40      19.50     16.86      17.65   28.26   21.46
Pune             14.65      19.43     13.87      14.14   28.57   21.41


## Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [66]:
loss_matrix = new_profit < 0
rows, cols = np.where(loss_matrix)
if len(rows) == 0:
    print("No store-category combination becomes loss-making after discounts.")
else:
    for r, c in zip(rows, cols):
        print(f"{stores[r]} | {categories[c]}")

No store-category combination becomes loss-making after discounts.


## Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

In [67]:
total_discount_impact = discount_amount.sum()
print("Total revenue lost due to discounts:", total_discount_impact)

Total revenue lost due to discounts: 1146350.0


## Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

In [68]:
store_discount_loss = discount_amount.sum(axis=1)
idx = np.argmax(store_discount_loss)
print("Most affected store:", stores[idx])
print("Revenue lost:", store_discount_loss[idx])

Most affected store: Mumbai
Revenue lost: 277150.0


# Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [69]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

## Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [70]:
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
print(pd.DataFrame(tax_collection, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture   Beauty   Sports
Bengaluru     153000.0    21000.0   37200.0    49500.0  34200.0  27000.0
Hyderabad     140400.0    23000.0   35400.0    55800.0  37800.0  28800.0
Chennai       165600.0    19500.0   40800.0    46800.0  33300.0  25800.0
Mumbai        189000.0    25500.0   45000.0    62100.0  45000.0  34800.0
Pune          124200.0    20250.0   33600.0    40500.0  31500.0  24600.0


## Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

In [71]:
sales_including_tax = sales_data + tax_collection
print(pd.DataFrame(sales_including_tax, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture    Beauty    Sports
Bengaluru    1003000.0   441000.0  347200.0   324500.0  224200.0  252000.0
Hyderabad     920400.0   483000.0  330400.0   365800.0  247800.0  268800.0
Chennai      1085600.0   409500.0  380800.0   306800.0  218300.0  240800.0
Mumbai       1239000.0   535500.0  420000.0   407100.0  295000.0  324800.0
Pune          814200.0   425250.0  313600.0   265500.0  206500.0  229600.0


## Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [72]:
store_tax = tax_collection.sum(axis=1)
for store, tax in zip(stores, store_tax):
    print(f"{store}: {tax}")

Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0


## Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [73]:
category_tax = tax_collection.sum(axis=0)
for category, tax in zip(categories, category_tax):
    print(f"{category}: {tax}")

Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0


## Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

In [74]:
idx = np.argmax(store_tax)
print("Highest tax-contributing store:", stores[idx])
print("Tax collected:", store_tax[idx])

Highest tax-contributing store: Mumbai
Tax collected: 401400.0


# Part 12: Array Modification

## Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [75]:
updated_sales = sales_data.copy()
updated_sales[4, 0] = 740000
print("Original Pune Electronics sales:", sales_data[4,0])
print("Updated Pune Electronics sales:", updated_sales[4,0])

Original Pune Electronics sales: 690000
Updated Pune Electronics sales: 740000


## Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [76]:
updated_cost = cost_data.copy()
updated_cost[:, 4] = updated_cost[:, 4] * 0.92
print(pd.DataFrame(updated_cost, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     205000  115000  160000
Hyderabad       590000     350000    210000     225000  128800  170000
Chennai         700000     295000    245000     195000  110400  155000
Mumbai          790000     390000    265000     250000  151800  205000
Pune            530000     310000    205000     170000  105800  145000


## Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [77]:
updated_furniture_cost = cost_data.copy()
updated_furniture_cost[:, 3] = updated_furniture_cost[:, 3] * 1.12
print(pd.DataFrame(updated_furniture_cost, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     229600  125000  160000
Hyderabad       590000     350000    210000     252000  140000  170000
Chennai         700000     295000    245000     218400  120000  155000
Mumbai          790000     390000    265000     280000  165000  205000
Pune            530000     310000    205000     190400  115000  145000


## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()

In [78]:
closed_sales = np.delete(sales_data, 4, axis=0)
closed_cost = np.delete(cost_data, 4, axis=0)
closed_stores = np.delete(stores, 4)
print("Stores after closure:", closed_stores)
print("Sales data after closure:")
print(closed_sales)
print("Cost data after closure:")
print(closed_cost)

Stores after closure: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
Sales data after closure:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
Cost data after closure:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


## Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.

In [79]:
delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])
sales_with_delhi = np.vstack((sales_data, delhi_sales))
cost_with_delhi = np.vstack((cost_data, delhi_cost))
stores_with_delhi = np.append(stores, "Delhi")
print("Stores:", stores_with_delhi)
print("Sales shape:", sales_with_delhi.shape)
print("Cost shape:", cost_with_delhi.shape)

Stores: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
Sales shape: (6, 6)
Cost shape: (6, 6)


## Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.

In [80]:
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])
home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])
sales_with_home = np.column_stack((sales_data, home_appliance_sales))
cost_with_home = np.column_stack((cost_data, home_appliance_cost))
categories_with_home = np.append(categories, "Home Appliances")
print("Categories:", categories_with_home)
print("Sales shape:", sales_with_home.shape)
print("Cost shape:", cost_with_home.shape)

Categories: ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']
Sales shape: (5, 7)
Cost shape: (5, 7)


# Part 13: Sorting and Ranking

## Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [81]:
store_totals = sales_data.sum(axis=1)
order = np.argsort(store_totals)
for idx in order:
    print(f"{stores[idx]}: {store_totals[idx]}")

Pune: 1980000
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000


## Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

In [82]:
store_profits = profit_data.sum(axis=1)
order = np.argsort(store_profits)[::-1]
for rank, idx in enumerate(order, start=1):
    print(f"{rank}. {stores[idx]}: {store_profits[idx]}")

1. Mumbai: 755000
2. Hyderabad: 610000
3. Bengaluru: 605000
4. Chennai: 600000
5. Pune: 505000


## Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

In [83]:
category_totals = sales_data.sum(axis=0)
order = np.argsort(category_totals)[::-1]
for idx in order:
    print(f"{categories[idx]}: {category_totals[idx]}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Sports: 1175000
Beauty: 1010000


## Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name

In [84]:
flat_order = np.argsort(sales_data.ravel())[::-1][:3]
for flat_idx in flat_order:
    r, c = np.unravel_index(flat_idx, sales_data.shape)
    print(f"Sales: {sales_data[r,c]} | Store: {stores[r]} | Category: {categories[c]}")

Sales: 1050000 | Store: Mumbai | Category: Electronics
Sales: 920000 | Store: Chennai | Category: Electronics
Sales: 850000 | Store: Bengaluru | Category: Electronics


## Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [85]:
flat_order = np.argsort(profit_data.ravel())[:3]
for flat_idx in flat_order:
    r, c = np.unravel_index(flat_idx, profit_data.shape)
    print(f"Profit: {profit_data[r,c]} | Store: {stores[r]} | Category: {categories[c]}")

Profit: 55000 | Store: Pune | Category: Furniture
Profit: 60000 | Store: Pune | Category: Sports
Profit: 60000 | Store: Chennai | Category: Sports


# Part 14: Statistical Analysis