# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

# Part 1: Dataset Creation

In [45]:
import numpy as np
import pandas as pd

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

df_sales=pd.DataFrame(sales_data,index=stores,columns=categories)
print("\n",df_sales)

df_cost=pd.DataFrame(cost_data,index=stores,columns=categories)
print("\n",df_cost)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderabad       780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  2

# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

In [46]:
print(f"dimensions of sales_data: {sales_data.ndim}\nshape of sales_data: {sales_data.shape}\ntotal no.of sales_data values: {sales_data.size}\ndata type of sales_data: {type(sales_data)}\nmemory occupied of sales_data: {sales_data.nbytes}")

dimensions of sales_data: 2
shape of sales_data: (5, 6)
total no.of sales_data values: 30
data type of sales_data: <class 'numpy.ndarray'>
memory occupied of sales_data: 240


## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

In [47]:
print(len(stores))
print(len(categories))
print(df_sales.size)

5
6
30


## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

In [48]:
folat32=sales_data.astype(np.float32)
folat64=sales_data.astype(np.float64)

print(f"float32: {folat32.nbytes} ,folat64: {folat64.nbytes}")

print(f"Memory saved: {folat64.nbytes - folat32.nbytes} bytes ({((folat64.nbytes - folat32.nbytes) / folat64.nbytes * 100):.1f}% reduction)")

float32: 120 ,folat64: 240
Memory saved: 120 bytes (50.0% reduction)


# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [49]:
print(df_sales.loc["Bengaluru"])

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Sports         225000
Name: Bengaluru, dtype: int64


## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [50]:
print(sum(df_cost.loc["Mumbai"]))

2065000


## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

In [62]:
print(df_sales.loc[:,df_sales.columns == "Electronics"])

           Electronics
Bengaluru       850000
Hyderabad       780000
Chennai         920000
Mumbai         1050000
Pune            690000


## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

In [63]:
print(df_cost.loc[:,df_cost.columns=="Clothing"])

           Clothing
Bengaluru    220000
Hyderabad    210000
Chennai      245000
Mumbai       265000
Pune         205000


## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

In [67]:
furniture_sales=df_sales.loc["Hyderabad",df_sales.columns=="Furniture"].item()
furniture_cost=df_cost.loc["Hyderabad",df_cost.columns=="Furniture"].item()
furniture_profit=furniture_sales-furniture_cost
print(f"furniture_sales:{furniture_sales}\nfurniture_cost:{furniture_cost}\nfurniture_profit:{furniture_profit}")

furniture_sales:310000
furniture_cost:225000
furniture_profit:85000


## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

In [79]:
chennai=df_sales.iloc[2,1:4]
print(chennai)

Groceries    390000
Clothing     340000
Furniture    260000
Name: Chennai, dtype: int64


## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

In [ ]:
da = df_sales.loc[["Bengaluru", "Chennai", "Pune"],["Electronics", "Clothing", "Beauty"]]  
print(da)

           Electronics  Clothing  Beauty
Bengaluru       850000    310000  190000
Chennai         920000    340000  185000
Pune            690000    280000  175000


# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [119]:
revenue_by_stores=df_sales.sum(axis=1)
print(f"total sales revenue generated by all stores: {sum(revenue_by_stores)}")
revenue_by_categories=df_sales.sum(axis=0)
print(f"total sales revenue generated by all categories :{sum(revenue_by_categories)}")

total sales revenue generated by all stores: 11675000
total sales revenue generated by all categories :11675000


## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [164]:
for i in df_sales.index:
    print(f"{i}: {sum(df_sales.loc[i])}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [165]:
print(df_sales.sum(axis=0))

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64


## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
print(df_sales.mean(axis=1))

Bengaluru    378333.333333
Hyderabad    382500.000000
Chennai      385000.000000
Mumbai       470000.000000
Pune         330000.000000
dtype: float64


## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [176]:
print(df_sales.mean(axis=0))

Electronics    858000.0
Groceries      437000.0
Clothing       320000.0
Furniture      283000.0
Beauty         202000.0
Sports         235000.0
dtype: float64


## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

In [186]:
print(np.argmax(df_sales.index))
print(np.max(df_sales.index))
print(np.max(df_sales.sum(axis=1)))

4
Pune
2820000


## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

In [202]:
lowest_sale=np.argmin(df_sales.sum(axis=1).values)
print(df_sales.index[lowest_sale])

Pune


## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [233]:
high_sale=np.argmax(df_sales.sum(axis=0).values)
print(df_sales[categories[high_sale]])

Bengaluru     850000
Hyderabad     780000
Chennai       920000
Mumbai       1050000
Pune          690000
Name: Electronics, dtype: int64


## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [234]:
high_sale=np.argmin(df_sales.sum(axis=0).values)
print(df_sales[categories[high_sale]])

Bengaluru    190000
Hyderabad    210000
Chennai      185000
Mumbai       250000
Pune         175000
Name: Beauty, dtype: int64


# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [236]:
print(np.sum(cost_data))

8600000
